Dataset Overview

By: Josh Navarro

Goal: Learn how to correctly look into the dataset overview in Jupyter Notebook using Python Pandas

Data: Synthetic by ChatGPT

In [32]:
# Imports that we will be using
import pandas as pd
import numpy as np

In [33]:
# Create the data
df = pd.DataFrame({
    "student_id": [101, 102, 103, 104, 105, 106, 107, 108],
    "name": ["Alex", "Maria", "James", "Sofia", "Daniel", "Emma", "Chris", "Olivia"],
    "age": [20, 21, 19, 22, np.nan, 20, 23, 21],
    "major": ["Business", "Data Science", "Computer Science", "Business", "Math", "Data Science", "Math", None],
    "gpa": [3.4, 3.8, 3.1, 3.6, 2.9, np.nan, 3.7, 3.5],
    "credits_completed": [45, 60, 30, 75, 90, 50, 80, 65],
    "graduated": [False, False, False, False, True, False, True, False]
})

df

,student_id,name,age,major,gpa,credits_completed,graduated
0,101,Alex,20.0,Business,3.4,45,False
1,102,Maria,21.0,Data Science,3.8,60,False
2,103,James,19.0,Computer Science,3.1,30,False
3,104,Sofia,22.0,Business,3.6,75,False
4,105,Daniel,NaN,Math,2.9,90,True
5,106,Emma,20.0,Data Science,NaN,50,False
6,107,Chris,23.0,Math,3.7,80,True
7,108,Olivia,21.0,None,3.5,65,False

Dataset overview methods in Pandas

In [34]:
# Create a copy of the dataframe
over_df = df.copy()

1 Viewing the first rows

To view the first 5 rows you can use the function .head(), by passing a number as the first argument you can change the amount of row shown

In [35]:
# Show the first 5 rows
over_df.head()

,student_id,name,age,major,gpa,credits_completed,graduated
0,101,Alex,20.0,Business,3.4,45,False
1,102,Maria,21.0,Data Science,3.8,60,False
2,103,James,19.0,Computer Science,3.1,30,False
3,104,Sofia,22.0,Business,3.6,75,False
4,105,Daniel,NaN,Math,2.9,90,True

In [36]:
# Show the first 10 rows
over_df.head(10)

,student_id,name,age,major,gpa,credits_completed,graduated
0,101,Alex,20.0,Business,3.4,45,False
1,102,Maria,21.0,Data Science,3.8,60,False
2,103,James,19.0,Computer Science,3.1,30,False
3,104,Sofia,22.0,Business,3.6,75,False
4,105,Daniel,NaN,Math,2.9,90,True
5,106,Emma,20.0,Data Science,NaN,50,False
6,107,Chris,23.0,Math,3.7,80,True
7,108,Olivia,21.0,None,3.5,65,False

2 Viewing the last rows

To view the last rows in the dataframe you need to use the .tail() fucntion, which you can pass a number as the first argument to change the amount of rows

In [37]:
# View the last 5 rows in the dataframe
over_df.tail()

   student_id    name   age         major  gpa  credits_completed  graduated
3         104   Sofia  22.0      Business  3.6                 75      False
4         105  Daniel   NaN          Math  2.9                 90       True
5         106    Emma  20.0  Data Science  NaN                 50      False
6         107   Chris  23.0          Math  3.7                 80       True
7         108  Olivia  21.0          None  3.5                 65      False

In [38]:
# Viewing the last 3 rows in the dataframe
over_df.tail(3)

   student_id    name   age         major  gpa  credits_completed  graduated
5         106    Emma  20.0  Data Science  NaN                 50      False
6         107   Chris  23.0          Math  3.7                 80       True
7         108  Olivia  21.0          None  3.5                 65      False

3 Check the shape of the DataFrame

Checking the shape of the Dataframe you need to use the function of .shape

In [39]:
# Check the shape of the dataframe
over_df.shape
# (8, 7) 8 is the rows and then 7 is columns

(8, 7)

4 Viewing the Column Names

To view the columns you need to use the .columns function

In [40]:
# Check the columns in the dataframe
over_df.columns

Index(['student_id', 'name', 'age', 'major', 'gpa', 'credits_completed',
       'graduated'],
      dtype='object')

In [41]:
# Put the columns into a list for further checking
over_df_columns = over_df.columns.tolist()
# Check the list
over_df_columns

['student_id', 'name', 'age', 'major', 'gpa', 'credits_completed', 'graduated']

5 Checking Data types

Checking data types in the dataframe you need to use the function of .dtypes

In [42]:
# Check the datatypes 
over_df.dtypes

student_id             int64
name                  object
age                  float64
major                 object
gpa                  float64
credits_completed      int64
graduated               bool
dtype: object

6 Get General dataset information

To get the general dataset information you need to use the function .info()

In [43]:
# Check the general information of the dataframe
over_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   student_id         8 non-null      int64
 1   name               8 non-null      object
 2   age                7 non-null      float64
 3   major              7 non-null      object
 4   gpa                7 non-null      float64
 5   credits_completed  8 non-null      int64
 6   graduated          8 non-null      bool
dtypes: bool(1), float64(2), int64(2), object(2)
memory usage: 524.0+ bytes

7 Summary Stats for numeric columns

For summary stats for the numeric columns you can use the function .describe()

In [44]:
# Check the summary stats for the dataframe
over_df.describe()

       student_id        age       gpa  credits_completed
count     8.00000   7.000000  7.000000           8.000000
mean    104.50000  20.857143  3.428571          61.875000
std       2.44949   1.345185  0.325137          19.809359
min     101.00000  19.000000  2.900000          30.000000
25%     102.75000  20.000000  3.250000          48.750000
50%     104.50000  21.000000  3.500000          62.500000
75%     106.25000  21.500000  3.650000          76.250000
max     108.00000  23.000000  3.800000          90.000000

8 Summary Stats for All Columns

To find the summary for All of the columns use the function of .describe() but include the argument of include="all"

In [45]:
# Check the summary stats for all of the dataframe
over_df.describe(include = "all")

,student_id,name,age,major,gpa,credits_completed,graduated
count,8.00000,8,7.000000,7,7.000000,8.000000,8
unique,NaN,8,NaN,4,NaN,NaN,2
top,NaN,Alex,NaN,Business,NaN,NaN,False
freq,NaN,1,NaN,2,NaN,NaN,6
mean,104.50000,NaN,20.857143,NaN,3.428571,61.875000,NaN
std,2.44949,NaN,1.345185,NaN,0.325137,19.809359,NaN
min,101.00000,NaN,19.000000,NaN,2.900000,30.000000,NaN
25%,102.75000,NaN,20.000000,NaN,3.250000,48.750000,NaN
50%,104.50000,NaN,21.000000,NaN,3.500000,62.500000,NaN
75%,106.25000,NaN,21.500000,NaN,3.650000,76.250000,NaN
max,108.00000,NaN,23.000000,NaN,3.800000,90.000000,NaN

9 Check Missing Values

To check the missing values, you use the fucntion of .isna(), and the function of .sum()

In [46]:
# To check the for the na rows
over_df.isna().sum()

student_id           0
name                 0
age                  1
major                1
gpa                  1
credits_completed    0
graduated            0
dtype: int64

In [47]:
# Another way to check for the NA rows
over_df.isnull().sum()

student_id           0
name                 0
age                  1
major                1
gpa                  1
credits_completed    0
graduated            0
dtype: int64

10 Check Percentage of Missing Values

To find the percentage of missing values you use the function of .isna() and then the .mean() then times it by 100

In [48]:
# Find the percentage of missing values in the dataframe
over_df.isna().mean() * 100

student_id            0.0
name                  0.0
age                  12.5
major                12.5
gpa                  12.5
credits_completed     0.0
graduated             0.0
dtype: float64

11 Check the duplicate rows

To check the duplicate rows you can use the .duplicate() and .sum() functions to find the count of the exact duplicate rows

In [49]:
# Check for duplicate rows
over_df.duplicated().sum()

np.int64(0)

12 View Unique Values in a Column

View the unique values that are found in a specific column, you use filtering and then the function of .unique()

In [50]:
# Find the unique values in the column major
over_df['major'].unique()

array(['Business', 'Data Science', 'Computer Science', 'Math', None],
      dtype=object)

13 Count of Unique values in each columnn

To count the number of unique values in each of the columns you need to use the function of .nunique()

In [51]:
# Find the number of unique vales in each of the cols
over_df.nunique()

student_id           8
name                 8
age                  5
major                4
gpa                  7
credits_completed    8
graduated            2
dtype: int64

14 Count values in a column

Counting the values in a column you do filtering and add the function of .value_counts()

In [52]:
# Count the values that are in the column of major
over_df['major'].value_counts()

major
Business            2
Data Science        2
Math                2
Computer Science    1
Name: count, dtype: int64

In [53]:
# Adding the dropna=False argument includes the missing values
over_df['major'].value_counts(dropna = False)

major
Business            2
Data Science        2
Math                2
Computer Science    1
None                1
Name: count, dtype: int64

15 Check index information

Checking the index information you need to use the function of .index

In [54]:
# Check the index info
over_df.index

RangeIndex(start=0, stop=8, step=1)

In [55]:
# To reset the index after messy filtering or sorting
over_df.reset_index(drop=True)

,student_id,name,age,major,gpa,credits_completed,graduated
0,101,Alex,20.0,Business,3.4,45,False
1,102,Maria,21.0,Data Science,3.8,60,False
2,103,James,19.0,Computer Science,3.1,30,False
3,104,Sofia,22.0,Business,3.6,75,False
4,105,Daniel,NaN,Math,2.9,90,True
5,106,Emma,20.0,Data Science,NaN,50,False
6,107,Chris,23.0,Math,3.7,80,True
7,108,Olivia,21.0,None,3.5,65,False