Dataset Overview

By: Josh Navarro

Goal: Learn how to correctly look into the dataset overview in Jupyter Notebook using Python Pandas

Data: Synthetic by ChatGPT

In [2]:
# Imports that we will be using
import pandas as pd
import numpy as np

In [3]:
# Create the data
df = pd.DataFrame({
    "student_id": [101, 102, 103, 104, 105, 106, 107, 108],
    "name": ["Alex", "Maria", "James", "Sofia", "Daniel", "Emma", "Chris", "Olivia"],
    "age": [20, 21, 19, 22, np.nan, 20, 23, 21],
    "major": ["Business", "Data Science", "Computer Science", "Business", "Math", "Data Science", "Math", None],
    "gpa": [3.4, 3.8, 3.1, 3.6, 2.9, np.nan, 3.7, 3.5],
    "credits_completed": [45, 60, 30, 75, 90, 50, 80, 65],
    "graduated": [False, False, False, False, True, False, True, False]
})

df

,student_id,name,age,major,gpa,credits_completed,graduated
0,101,Alex,20.0,Business,3.4,45,False
1,102,Maria,21.0,Data Science,3.8,60,False
2,103,James,19.0,Computer Science,3.1,30,False
3,104,Sofia,22.0,Business,3.6,75,False
4,105,Daniel,NaN,Math,2.9,90,True
5,106,Emma,20.0,Data Science,NaN,50,False
6,107,Chris,23.0,Math,3.7,80,True
7,108,Olivia,21.0,None,3.5,65,False

Dataset overview methods in Pandas

In [4]:
# Create a copy of the dataframe
over_df = df.copy()

1 Viewing the first rows

To view the first 5 rows you can use the function .head(), by passing a number as the first argument you can change the amount of row shown

In [5]:
# Show the first 5 rows
over_df.head()

,student_id,name,age,major,gpa,credits_completed,graduated
0,101,Alex,20.0,Business,3.4,45,False
1,102,Maria,21.0,Data Science,3.8,60,False
2,103,James,19.0,Computer Science,3.1,30,False
3,104,Sofia,22.0,Business,3.6,75,False
4,105,Daniel,NaN,Math,2.9,90,True

In [7]:
# Show the first 10 rows
over_df.head(10)

,student_id,name,age,major,gpa,credits_completed,graduated
0,101,Alex,20.0,Business,3.4,45,False
1,102,Maria,21.0,Data Science,3.8,60,False
2,103,James,19.0,Computer Science,3.1,30,False
3,104,Sofia,22.0,Business,3.6,75,False
4,105,Daniel,NaN,Math,2.9,90,True
5,106,Emma,20.0,Data Science,NaN,50,False
6,107,Chris,23.0,Math,3.7,80,True
7,108,Olivia,21.0,None,3.5,65,False

2 Viewing the last rows

To view the last rows in the dataframe you need to use the .tail() fucntion, which you can pass a number as the first argument to change the amount of rows

In [8]:
# View the last 5 rows in the dataframe
over_df.tail()

   student_id    name   age         major  gpa  credits_completed  graduated
3         104   Sofia  22.0      Business  3.6                 75      False
4         105  Daniel   NaN          Math  2.9                 90       True
5         106    Emma  20.0  Data Science  NaN                 50      False
6         107   Chris  23.0          Math  3.7                 80       True
7         108  Olivia  21.0          None  3.5                 65      False

In [9]:
# Viewing the last 3 rows in the dataframe
over_df.tail(3)

   student_id    name   age         major  gpa  credits_completed  graduated
5         106    Emma  20.0  Data Science  NaN                 50      False
6         107   Chris  23.0          Math  3.7                 80       True
7         108  Olivia  21.0          None  3.5                 65      False

3 Check the shape of the DataFrame

4 Viewing the Column Names

5 Checking Data types

6 Get General dataset information

7 Summary Stats for numeric columns

8 Summary Stats for All Columns

9 Check Missing Values

10 Check Percentage of Missing Values

11 Check the duplicate rows

12 View Unique Values in a Column

13 Count of Unique values in each columnn

14 Count values in a column

15 Check index information