Grouping Aggregation

By: Josh Navarro

Goal: Learn grouping aggregation in jupyter notebook using python pandas

Data: Create by ChatGPT

In [1]:
# Import that we are going to be using
import pandas as pd
import numpy as np

In [2]:
# Creating the dataframe

data = {
    "order_id": [
        1001, 1002, 1003, 1004, 1005,
        1006, 1007, 1008, 1009, 1010,
        1011, 1012, 1013, 1014, 1015,
        1016, 1017, 1018, 1019, 1020
    ],
    "customer_id": [
        "C001", "C002", "C003", "C001", "C004",
        "C002", "C005", "C003", "C006", "C004",
        "C001", "C007", "C005", "C006", "C002",
        "C008", "C003", "C007", "C004", "C005"
    ],
    "region": [
        "West", "South", "East", "West", "North",
        "South", "West", "East", "North", "North",
        "West", "South", "West", "North", "South",
        "East", "East", "South", "North", "West"
    ],
    "product_category": [
        "Electronics", "Clothing", "Home", "Electronics", "Clothing",
        "Home", "Electronics", "Clothing", "Home", "Electronics",
        "Home", "Clothing", "Clothing", "Electronics", "Electronics",
        "Home", "Electronics", "Home", "Clothing", "Electronics"
    ],
    "sales_channel": [
        "Online", "In-Store", "Online", "Mobile App", "Online",
        "In-Store", "Online", "Mobile App", "Online", "In-Store",
        "Mobile App", "Online", "In-Store", "Mobile App", "Online",
        "Online", "In-Store", "Mobile App", "Online", "In-Store"
    ],
    "units_sold": [
        2, 1, 4, 1, 3,
        2, 5, 2, 3, 1,
        4, 2, 1, 2, 3,
        5, 1, 2, 4, 2
    ],
    "unit_price": [
        699.99, 49.99, 89.99, 799.99, 39.99,
        129.99, 599.99, 59.99, 99.99, 899.99,
        79.99, 45.99, 55.99, 749.99, 649.99,
        119.99, 999.99, 139.99, 35.99, 549.99
    ],
    "discount_rate": [
        0.10, 0.05, 0.00, 0.15, 0.10,
        0.00, 0.20, 0.05, 0.10, 0.00,
        0.05, 0.10, 0.00, 0.15, 0.10,
        0.05, 0.20, 0.00, 0.10, 0.05
    ],
    "returned": [
        "No", "No", "Yes", "No", "No",
        "No", "No", "Yes", "No", "No",
        "No", "No", "No", "No", "Yes",
        "No", "No", "Yes", "No", "No"
    ]
}

df = pd.DataFrame(data)

df["revenue"] = df["units_sold"] * df["unit_price"] * (1 - df["discount_rate"])

df

,order_id,customer_id,region,product_category,sales_channel,units_sold,unit_price,discount_rate,returned,revenue
0,1001,C001,West,Electronics,Online,2,699.99,0.10,No,1259.9820
1,1002,C002,South,Clothing,In-Store,1,49.99,0.05,No,47.4905
2,1003,C003,East,Home,Online,4,89.99,0.00,Yes,359.9600
3,1004,C001,West,Electronics,Mobile App,1,799.99,0.15,No,679.9915
4,1005,C004,North,Clothing,Online,3,39.99,0.10,No,107.9730
5,1006,C002,South,Home,In-Store,2,129.99,0.00,No,259.9800
6,1007,C005,West,Electronics,Online,5,599.99,0.20,No,2399.9600
7,1008,C003,East,Clothing,Mobile App,2,59.99,0.05,Yes,113.9810
8,1009,C006,North,Home,Online,3,99.99,0.10,No,269.9730
9,1010,C004,North,Electronics,In-Store,1,899.99,0.00,No,899.9900
10,1011,C001,West,Home,Mobile App,4,79.99,0.05,No,303.9620
11,1012,C007,South,Clothing,Online,2,45.99,0.10,No,82.7820
12,1013,C005,West,Clothing,In-Store,1,55.99,0.00,No,55.9900
13,1014,C006,North,Electronics,Mobile App,2,749.99,0.15,No,1274.9830
14,1015,C002,South,Electronics,Online,3,649.99,0.10,Yes,1754.9730
15,1016,C008,East,Home,Online,5,119.99,0.05,No,569.9525
16,1017,C003,East,Electronics,In-Store,1,999.99,0.20,No,799.9920
17,1018,C007,South,Home,Mobile App,2,139.99,0.00,Yes,279.9800
18,1019,C004,North,Clothing,Online,4,35.99,0.10,No,129.5640
19,1020,C005,West,Electronics,In-Store,2,549.99,0.05,No,1044.9810

Grouping Aggregation

Grouping means splitting your datastet into groups based upon the columns chosen, and having a summary for a specific aggregation

In [3]:
# Create a copy of the dataframe
group_df = df.copy()

1 Group by One Column

To group by one column you use the .groupby() function and pass a column, and mulitply by another column and add an aggregation

In [4]:
# Group by the region, find the total revenue
group_df.groupby('region')['revenue'].sum()

region
East     1843.8855
North    2682.4830
South    2425.2055
West     5744.8665
Name: revenue, dtype: float64

2 Group by One Column and Calculate Average

To group by one column and to caluclate the average you use the .groupby() function and use the aggregation of .mean()

In [5]:
# Group by the sales_channel 
# and find the average revenue
group_df.groupby("sales_channel")['revenue'].mean()

sales_channel
In-Store      518.070583
Mobile App    530.579500
Online        770.568833
Name: revenue, dtype: float64

3 Group by Mulitple Columns

Grouping by mulitple columns you use the .groupby() but pass a list of columns, and then multiply by a column and add a aggregation to it

Note: Order does matter

In [6]:
# Group by both the region and product_catoegory 
# find the total revenue
group_df.groupby(['region', 'product_category'])['revenue'].sum()

region  product_category
East    Clothing             113.9810
        Electronics          799.9920
        Home                 929.9125
North   Clothing             237.5370
        Electronics         2174.9730
        Home                 269.9730
South   Clothing             130.2725
        Electronics         1754.9730
        Home                 539.9600
West    Clothing              55.9900
        Electronics         5384.9145
        Home                 303.9620
Name: revenue, dtype: float64

4 Count Rows in Each group

Counting the rows in each of the columns you use the function .groupby() and .size()

In [7]:
# Find the rows for the group region
group_df.groupby('region').size()

region
East     4
North    5
South    5
West     6
dtype: int64

5 Count Non-Missing Values

Counting the non-missing values you you use the .groupby() and multiply the by a column and add the aggregation of .count()

In [8]:
# Group by the region count the rows in the revenue
group_df.groupby("region")["revenue"].count()

region
East     4
North    5
South    5
West     6
Name: revenue, dtype: int64

6 Count Unique Values

Counting the unique values you need to use .groupby(), multi column, and then .nunique()

In [9]:
# Groupby the region and find 
# the number of unique customers
group_df.groupby("region")["revenue"].count()

region
East     4
North    5
South    5
West     6
Name: revenue, dtype: int64

7 Use Multiple Aggregation on One column

Using multiple aggregation on one column you need to use the .groupby(), and then multi by a column, and then the .agg() function but pass a list of aggregations

In [10]:
# group by the product category, a 
# find the total, avg, etc revenue
group_df.groupby("product_category")["revenue"].agg(["sum", "mean", "min", "max"])

                         sum         mean       min        max
product_category
Clothing            537.7805    89.630083   47.4905   129.5640
Electronics       10114.8525  1264.356563  679.9915  2399.9600
Home               2043.8075   340.634583  259.9800   569.9525

8 Use different aggregations for Different Columns

Using different aggregations for different columns, you do the .groupby() and then use .agg() but pass a dictionary of "column" : "aggregation"

In [11]:
group_df.groupby("region").agg({
    "revenue": "sum",
    "units_sold": "sum",
    "unit_price": "mean",
    "customer_id": "nunique"
})

          revenue  units_sold  unit_price  customer_id
region
East    1843.8855          12  317.490000            2
North   2682.4830          13  365.190000            2
South   2425.2055          10  203.190000            2
West    5744.8665          15  464.323333            2

9 Rename Aggregated Columns

Renaming the aggregated columns you do the .groupby(), then the .agg() but pass these name = ('column', 'agg')

In [12]:
# Create the summary table
summary = group_df.groupby("region").agg(
    total_revenue=("revenue", "sum"),
    average_revenue=("revenue", "mean"),
    total_units=("units_sold", "sum"),
    unique_customers=("customer_id", "nunique"),
    order_count=("order_id", "count")
).reset_index()

summary

,region,total_revenue,average_revenue,total_units,unique_customers,order_count
0,East,1843.8855,460.971375,12,2,4
1,North,2682.4830,536.496600,13,2,5
2,South,2425.2055,485.041100,10,2,5
3,West,5744.8665,957.477750,15,2,6

10 Filter Group With GroupBy

After grouping and saving it, you can use filtering on the saved variable

In [13]:
# Group by the product_category 
# and then find the total revenue
category_revenue = group_df.groupby("product_category")["revenue"].sum()
# Filter for those that have a 
# higher revenue than 2000
category_revenue[category_revenue > 2000]

product_category
Electronics    10114.8525
Home            2043.8075
Name: revenue, dtype: float64

11 Sort Grouped Results

To sort by the grouped results, you use the typical structure, and then you add the .sort_values()

In [14]:
# Group by region, find the 
# total revenue and sort in decending order
group_df.groupby("region")["revenue"].sum().sort_values(ascending=False)

region
West     5744.8665
North    2682.4830
South    2425.2055
East     1843.8855
Name: revenue, dtype: float64

12 Use as_index = False

Using the argument as_index = False you keep the grouped column as regular column

In [15]:
# Group by region and find the tolal 
# revenue keep grouped column a column 
group_df.groupby("region", as_index=False)["revenue"].sum()

  region    revenue
0   East  1843.8855
1  North  2682.4830
2  South  2425.2055
3   West  5744.8665

13 Transform Grouped Values Back to Original rows

Transforming grouped values to the original rows you do the same structure but you add the .transform() funcntion and pass the aggregation

In [16]:
# Group Region, and find revenue total compare to original
group_df["region_avg_revenue"] = group_df.groupby("region")["revenue"].transform("mean")

group_df[["order_id", "region", "revenue", "region_avg_revenue"]]

    order_id region    revenue  region_avg_revenue
0       1001   West  1259.9820          957.477750
1       1002  South    47.4905          485.041100
2       1003   East   359.9600          460.971375
3       1004   West   679.9915          957.477750
4       1005  North   107.9730          536.496600
5       1006  South   259.9800          485.041100
6       1007   West  2399.9600          957.477750
7       1008   East   113.9810          460.971375
8       1009  North   269.9730          536.496600
9       1010  North   899.9900          536.496600
10      1011   West   303.9620          957.477750
11      1012  South    82.7820          485.041100
12      1013   West    55.9900          957.477750
13      1014  North  1274.9830          536.496600
14      1015  South  1754.9730          485.041100
15      1016   East   569.9525          460.971375
16      1017   East   799.9920          460.971375
17      1018  South   279.9800          485.041100
18      1019  North   129.5640          536.496600
19      1020   West  1044.9810          957.477750

14 Rank within Groups

TO have ranks within the groups you can use the same structure as before but add the .rank() function

In [17]:
group_df["revenue_rank_in_region"] = group_df.groupby("region")["revenue"].rank(
    ascending=False
)

group_df[["order_id", "region", "revenue", "revenue_rank_in_region"]]

    order_id region    revenue  revenue_rank_in_region
0       1001   West  1259.9820                     2.0
1       1002  South    47.4905                     5.0
2       1003   East   359.9600                     3.0
3       1004   West   679.9915                     4.0
4       1005  North   107.9730                     5.0
5       1006  South   259.9800                     3.0
6       1007   West  2399.9600                     1.0
7       1008   East   113.9810                     4.0
8       1009  North   269.9730                     3.0
9       1010  North   899.9900                     2.0
10      1011   West   303.9620                     5.0
11      1012  South    82.7820                     4.0
12      1013   West    55.9900                     6.0
13      1014  North  1274.9830                     1.0
14      1015  South  1754.9730                     1.0
15      1016   East   569.9525                     2.0
16      1017   East   799.9920                     1.0
17      1018  South   279.9800                     2.0
18      1019  North   129.5640                     4.0
19      1020   West  1044.9810                     3.0

15 Get the Largest or Lowest value in each group 

To get the lowest or the largest you can ue the function .idmax() or .idxmin() at the end.

In [18]:
# For the largest
group_df.loc[group_df.groupby("region")["revenue"].idxmax()]

,order_id,customer_id,region,product_category,sales_channel,units_sold,unit_price,discount_rate,returned,revenue,region_avg_revenue,revenue_rank_in_region
16,1017,C003,East,Electronics,In-Store,1,999.99,0.20,No,799.992,460.971375,1.0
13,1014,C006,North,Electronics,Mobile App,2,749.99,0.15,No,1274.983,536.496600,1.0
14,1015,C002,South,Electronics,Online,3,649.99,0.10,Yes,1754.973,485.041100,1.0
6,1007,C005,West,Electronics,Online,5,599.99,0.20,No,2399.960,957.477750,1.0

In [19]:
# For the lowest
group_df.loc[group_df.groupby("region")["revenue"].idxmax()]

,order_id,customer_id,region,product_category,sales_channel,units_sold,unit_price,discount_rate,returned,revenue,region_avg_revenue,revenue_rank_in_region
16,1017,C003,East,Electronics,In-Store,1,999.99,0.20,No,799.992,460.971375,1.0
13,1014,C006,North,Electronics,Mobile App,2,749.99,0.15,No,1274.983,536.496600,1.0
14,1015,C002,South,Electronics,Online,3,649.99,0.10,Yes,1754.973,485.041100,1.0
6,1007,C005,West,Electronics,Online,5,599.99,0.20,No,2399.960,957.477750,1.0

17 Pivot Table as Grouped Summary 

Pivot table is another way to have a grouped summary

In [20]:
# Create a pivot table
pd.pivot_table(
    group_df,
    values="revenue",
    index="region",
    columns="product_category",
    aggfunc="sum"
)

product_category  Clothing  Electronics      Home
region
East              113.9810     799.9920  929.9125
North             237.5370    2174.9730  269.9730
South             130.2725    1754.9730  539.9600
West               55.9900    5384.9145  303.9620

18 Grouping Dates Example

Just an example of you can also group by the dates as well

In [21]:
# Create the order_date column
group_df["order_date"] = pd.date_range(start="2026-01-01", periods=len(df), freq="D")

In [22]:
group_df.groupby(group_df["order_date"].dt.month)["revenue"].sum()

order_date
1    12696.4405
Name: revenue, dtype: float64